# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
