# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userblog.Blog'),
            preserve_default=False,
        ),
    ]
