# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycomment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
