# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomment',
            name='comment',
            field=models.BooleanField(default=False),
        ),
    ]
