# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_mycomment_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomment',
            name='post_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
            preserve_default=False,
        ),
    ]
