# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('post', '0002_auto_20160601_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomment',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
            preserve_default=False,
        ),
    ]
