# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_commentadd_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentadd',
            name='postname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postadd', to='post.PostAdd'),
        ),
    ]
