# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20160602_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to=b'images/'),
            preserve_default=False,
        ),
    ]
