# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.BooleanField(default=True),
        ),
    ]
