# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20160411_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'/media/images/'),
        ),
    ]
