# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view',
        ),
        migrations.AddField(
            model_name='like',
            name='view',
            field=models.BooleanField(default=True),
        ),
    ]
