# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20160405_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='picture',
        ),
    ]
