# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_auto_20160412_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
