# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20160414_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
