# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_unlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='UnLike',
        ),
    ]
