# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_commentadd'),
        ('post', '0006_remove_commentadd_user'),
        ('post', '0012_postadd_video'),
    ]

    operations = [
    ]
