# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20160405_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='unlike',
            field=models.BooleanField(default=False),
        ),
    ]
