# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20160606_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 6, 6, 10, 2, 25, 754298))),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postviews', to='post.Post'),
        ),
    ]
