# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 10:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20160606_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 6, 10, 18, 55, 419620)),
        ),
    ]
