# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20160405_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlike',
            name='unlike',
            field=models.BooleanField(default=True),
        ),
    ]
