# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20160606_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 6, 13, 8, 4, 728378)),
        ),
    ]
