# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20160606_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view',
            new_name='views',
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 6, 13, 34, 18, 251874)),
        ),
    ]
