# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20160405_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlike',
            name='like',
        ),
        migrations.DeleteModel(
            name='UnLike',
        ),
    ]
