# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20160407_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycomment',
            name='user_name',
        ),
    ]
