# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profilepic',
        ),
        migrations.DeleteModel(
            name='userprof',
        ),
    ]
