# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_user_registrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user_registrations',
            new_name='user_register_name',
        ),
    ]
