# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20160409_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user_register_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
