# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20160401_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user_register_name',
        ),
    ]
