# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('category', '0004_remove_category_user_register_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user_register_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userauth.UserRegistration'),
            preserve_default=False,
        ),
    ]
