# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 06:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 5, 9, 6, 17, 2, 437536, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2016, 5, 9, 6, 17, 31, 113195, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2016, 5, 9, 6, 17, 39, 308211, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
