# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160509_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='date',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='username',
        ),
    ]
