# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160526_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 5, 26, 12, 4, 49, 46852, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
