# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160509_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='star',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='views',
        ),
    ]
