# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='designation',
            new_name='profession',
        ),
    ]
