# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160509_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.CharField(default=datetime.datetime(2016, 5, 9, 10, 5, 3, 499542, tzinfo=utc), max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='detail',
            field=models.TextField(default=datetime.datetime(2016, 5, 9, 10, 5, 10, 663317, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
