# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160509_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='detail',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='star',
            new_name='stars',
        ),
    ]
