# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160528_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='title',
            new_name='post_title',
        ),
    ]
