# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160509_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
        migrations.AddField(
            model_name='posts',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='/static/assets/images/blog'),
        ),
    ]
