# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_commentdata_replydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdata',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='replydata',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
