# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160530_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdata',
            name='userprofile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
