# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_commentdata_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdata',
            name='userprofile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
    ]
