# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160531_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
    ]
