# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_posts_total_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='replydata',
            name='userprofile',
            field=models.ForeignKey(blank=True, default=123, on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
            preserve_default=False,
        ),
    ]
