# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160509_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.CharField(default=datetime.datetime(2016, 5, 10, 11, 33, 37, 170571, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
