# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_posts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='user/profile_pictures/'),
        ),
    ]
