# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160511_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
    ]
