# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20160513_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='/home/ravi/project/media/user/profile_pictures/no-image.jpg', upload_to='/home/ravi/project/media/user/profile_pictures/'),
        ),
    ]
