# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20160513_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(default='user/profile_pictures/no-image.jpg', upload_to='user/profile_pictures/'),
        ),
    ]
