# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20160513_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='user/profile_pictures/'),
        ),
    ]
