# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20160514_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='user/profile_pictures/'),
        ),
    ]
