# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20160514_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='/media/user/profile_pictures/'),
        ),
    ]
