# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20160514_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='/media/user/profile_pictures/no-image.jpg', upload_to='/media/user/profile_pictures/'),
        ),
    ]
