# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 5, 17, 12, 48, 39, 183228, tzinfo=utc), max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
