# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20160518_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='user/profile_pictures/no-image.jpg', upload_to='user/profile_pictures/'),
        ),
    ]
