# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 5, 18, 10, 52, 51, 960959, tzinfo=utc), max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
