# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 5, 18, 10, 57, 53, 817151, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
