# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_userprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='uname',
        ),
    ]
