# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20160518_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uname',
            field=models.CharField(max_length=254),
        ),
    ]
