# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20160518_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='uname',
            new_name='name',
        ),
    ]
