# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_remove_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user/profile_pictures/no-image.jpg', upload_to='user/profile_pictures/'),
        ),
    ]
