# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 07:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_auto_20160519_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 5, 20, 7, 10, 13, 905549, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lives_in',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
