# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 06:20
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20160412_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobileno',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=0, max_length=128, null=True),
        ),
    ]
