# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='view',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
