# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'images/'),
        ),
    ]
