# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20160405_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
