# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_userregistration_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
