# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_auto_20160406_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='name',
        ),
    ]
